<?php
session_start();
require_once '../includes/config.php';
require_once '../assets/tcpdf/tcpdf.php';

if (!isset($_SESSION['user_id']) || $_SESSION['role'] != 'parent') {
    die("Access denied.");
}

$parent_id = $_SESSION['user_id'];
$child_id = $_GET['child_id'] ?? 0;
$status_filter = $_GET['status'] ?? 'all';

if ($child_id == 0) die("Invalid child");

// Get child info
$child_query = "SELECT child_name, dob FROM children WHERE child_id = '$child_id' AND parent_id = '$parent_id'";
$child_result = mysqli_query($conn, $child_query);
$child = mysqli_fetch_assoc($child_result);

if (!$child) die("Child not found");

// Get reports
$sql = "SELECT v.vaccine_name, b.booking_date, b.status, r.vaccination_date 
        FROM bookings b
        JOIN vaccines v ON b.vaccine_id = v.vaccine_id
        LEFT JOIN vaccination_reports r ON b.booking_id = r.booking_id
        WHERE b.child_id = '$child_id'";

if ($status_filter != 'all') {
    $sql .= " AND b.status = '$status_filter'";
}

$sql .= " ORDER BY b.booking_date DESC";
$result = mysqli_query($conn, $sql);

// Create PDF
$pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);
$pdf->AddPage();

// Title
$pdf->SetFont('helvetica', 'B', 16);
$pdf->Cell(0, 10, 'Vaccination Report', 0, 1, 'C');
$pdf->Ln(5);

// Child info
$pdf->SetFont('helvetica', '', 12);
$pdf->Cell(0, 8, 'Child: ' . $child['child_name'], 0, 1);
$pdf->Cell(0, 8, 'Date of Birth: ' . date('d/m/Y', strtotime($child['dob'])), 0, 1);
$pdf->Cell(0, 8, 'Report Date: ' . date('d F Y'), 0, 1);
$pdf->Ln(10);

// Table header
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell(80, 8, 'Vaccine', 1, 0, 'C');
$pdf->Cell(40, 8, 'Scheduled', 1, 0, 'C');
$pdf->Cell(40, 8, 'Completed', 1, 0, 'C');
$pdf->Cell(30, 8, 'Status', 1, 1, 'C');

// Table data
$pdf->SetFont('helvetica', '', 10);
while($row = mysqli_fetch_assoc($result)) {
    $status = ['Pending', 'Approved', 'Vaccinated', 'Rejected'][$row['status']];
    
    $pdf->Cell(80, 8, $row['vaccine_name'], 1, 0, 'L');
    $pdf->Cell(40, 8, date('d/m/Y', strtotime($row['booking_date'])), 1, 0, 'C');
    
    if ($row['vaccination_date']) {
        $pdf->Cell(40, 8, date('d/m/Y', strtotime($row['vaccination_date'])), 1, 0, 'C');
    } else {
        $pdf->Cell(40, 8, '-', 1, 0, 'C');
    }
    
    $pdf->Cell(30, 8, $status, 1, 1, 'C');
}

// Footer
$pdf->Ln(15);
$pdf->SetFont('helvetica', 'I', 9);
$pdf->Cell(0, 8, 'Generated by VaxPakistan Vaccination System', 0, 1, 'C');
$pdf->Cell(0, 8, date('d F Y, h:i A'), 0, 1, 'C');

// Output
$filename = 'Vaccination_Report_' . date('Ymd_His') . '.pdf';
$pdf->Output($filename, 'D');
?>